apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: python-app-docker
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'python-app-docker:latest'
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/georgfedermann/pyapp.git'
    type: Git
  strategy:
    dockerStrategy:
    type: Docker
  triggers:
    - imageChange:
        lastTriggeredImageID: >-
          172.30.1.1:5000/openshift/python@sha256:fa4a5d0676a56e7666bce355bbbaa8fa2737d2b9d04444d1f8ee383434da798e
      type: ImageChange
    - type: ConfigChange
    - generic:
        secret: 180ff4a80d9e0b81
      type: Generic
    - github:
        secret: 29f5db14d720531f
      type: GitHub

